# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches:
      - 'main'
      - 'fix/*'
      - 'feature/*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version:
          - 12.x
          - 14.x
          - 16.x
        include:
          - os: ubuntu-latest
            platform: x32
          - os: ubuntu-latest
            platform: x64
          - os: ubuntu-latest
            arch: armv7

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        arch: ${{ matrix.arch }}
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test:pretty
